name: Branch Checkout and System Info

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  JobWindows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Windows version | WINDOWS
        run: |
          echo Windows Version:
          Get-CimInstance Win32_OperatingSystem
  
  JobLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Display README.md content | LINUX
        run: |
          #cat README.md
          uname -a
    needs:
     - JobWindows
     
  check:
    name: Check Cert
    runs-on: ubuntu-latest
    steps:
      - name: Check Certificates
        uses: fengkx/cert-check@1.0.0
        with:
          gist_id: '32278de43b1c11c99c62b3e87d9eb5dba'
          sites: 'https://www.google.com.br'
          github_pat: ${{ secrets.TOKEN }}
    needs:
     - JobWindows
     - JobLinux
          


